// avlm_avls_1x1_mm_interconnect_1.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 21.1 842

`timescale 1 ps / 1 ps
module avlm_avls_1x1_mm_interconnect_1 (
		input  wire        clk_clk_clk,                                      //                                    clk_clk.clk
		input  wire        monitor_0_reset_sink_reset_bridge_in_reset_reset, // monitor_0_reset_sink_reset_bridge_in_reset.reset
		input  wire [11:0] monitor_0_m0_address,                             //                               monitor_0_m0.address
		output wire        monitor_0_m0_waitrequest,                         //                                           .waitrequest
		input  wire [3:0]  monitor_0_m0_burstcount,                          //                                           .burstcount
		input  wire [3:0]  monitor_0_m0_byteenable,                          //                                           .byteenable
		input  wire        monitor_0_m0_write,                               //                                           .write
		input  wire [31:0] monitor_0_m0_writedata,                           //                                           .writedata
		output wire [11:0] slave_0_s0_address,                               //                                 slave_0_s0.address
		output wire        slave_0_s0_write,                                 //                                           .write
		output wire        slave_0_s0_read,                                  //                                           .read
		input  wire [31:0] slave_0_s0_readdata,                              //                                           .readdata
		output wire [31:0] slave_0_s0_writedata,                             //                                           .writedata
		output wire [3:0]  slave_0_s0_burstcount,                            //                                           .burstcount
		output wire [3:0]  slave_0_s0_byteenable,                            //                                           .byteenable
		input  wire        slave_0_s0_readdatavalid,                         //                                           .readdatavalid
		input  wire        slave_0_s0_waitrequest                            //                                           .waitrequest
	);

	wire         monitor_0_m0_translator_avalon_universal_master_0_waitrequest;   // slave_0_s0_translator:uav_waitrequest -> monitor_0_m0_translator:uav_waitrequest
	wire  [31:0] monitor_0_m0_translator_avalon_universal_master_0_readdata;      // slave_0_s0_translator:uav_readdata -> monitor_0_m0_translator:uav_readdata
	wire         monitor_0_m0_translator_avalon_universal_master_0_debugaccess;   // monitor_0_m0_translator:uav_debugaccess -> slave_0_s0_translator:uav_debugaccess
	wire  [11:0] monitor_0_m0_translator_avalon_universal_master_0_address;       // monitor_0_m0_translator:uav_address -> slave_0_s0_translator:uav_address
	wire         monitor_0_m0_translator_avalon_universal_master_0_read;          // monitor_0_m0_translator:uav_read -> slave_0_s0_translator:uav_read
	wire   [3:0] monitor_0_m0_translator_avalon_universal_master_0_byteenable;    // monitor_0_m0_translator:uav_byteenable -> slave_0_s0_translator:uav_byteenable
	wire         monitor_0_m0_translator_avalon_universal_master_0_readdatavalid; // slave_0_s0_translator:uav_readdatavalid -> monitor_0_m0_translator:uav_readdatavalid
	wire         monitor_0_m0_translator_avalon_universal_master_0_lock;          // monitor_0_m0_translator:uav_lock -> slave_0_s0_translator:uav_lock
	wire         monitor_0_m0_translator_avalon_universal_master_0_write;         // monitor_0_m0_translator:uav_write -> slave_0_s0_translator:uav_write
	wire  [31:0] monitor_0_m0_translator_avalon_universal_master_0_writedata;     // monitor_0_m0_translator:uav_writedata -> slave_0_s0_translator:uav_writedata
	wire   [5:0] monitor_0_m0_translator_avalon_universal_master_0_burstcount;    // monitor_0_m0_translator:uav_burstcount -> slave_0_s0_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (12),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (4),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (12),
		.UAV_BURSTCOUNT_W            (6),
		.USE_READ                    (0),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (0),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (1),
		.UAV_CONSTANT_BURST_BEHAVIOR (1),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) monitor_0_m0_translator (
		.clk                    (clk_clk_clk),                                                     //                       clk.clk
		.reset                  (monitor_0_reset_sink_reset_bridge_in_reset_reset),                //                     reset.reset
		.uav_address            (monitor_0_m0_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (monitor_0_m0_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (monitor_0_m0_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (monitor_0_m0_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (monitor_0_m0_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (monitor_0_m0_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (monitor_0_m0_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (monitor_0_m0_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (monitor_0_m0_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (monitor_0_m0_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (monitor_0_m0_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (monitor_0_m0_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (monitor_0_m0_waitrequest),                                        //                          .waitrequest
		.av_burstcount          (monitor_0_m0_burstcount),                                         //                          .burstcount
		.av_byteenable          (monitor_0_m0_byteenable),                                         //                          .byteenable
		.av_write               (monitor_0_m0_write),                                              //                          .write
		.av_writedata           (monitor_0_m0_writedata),                                          //                          .writedata
		.av_beginbursttransfer  (1'b0),                                                            //               (terminated)
		.av_begintransfer       (1'b0),                                                            //               (terminated)
		.av_chipselect          (1'b0),                                                            //               (terminated)
		.av_read                (1'b0),                                                            //               (terminated)
		.av_readdata            (),                                                                //               (terminated)
		.av_readdatavalid       (),                                                                //               (terminated)
		.av_lock                (1'b0),                                                            //               (terminated)
		.av_debugaccess         (1'b0),                                                            //               (terminated)
		.uav_clken              (),                                                                //               (terminated)
		.av_clken               (1'b1),                                                            //               (terminated)
		.uav_response           (2'b00),                                                           //               (terminated)
		.av_response            (),                                                                //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                            //               (terminated)
		.av_writeresponsevalid  ()                                                                 //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (12),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (4),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (12),
		.UAV_BURSTCOUNT_W               (6),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (1),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) slave_0_s0_translator (
		.clk                    (clk_clk_clk),                                                     //                      clk.clk
		.reset                  (monitor_0_reset_sink_reset_bridge_in_reset_reset),                //                    reset.reset
		.uav_address            (monitor_0_m0_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (monitor_0_m0_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (monitor_0_m0_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (monitor_0_m0_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (monitor_0_m0_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (monitor_0_m0_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (monitor_0_m0_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (monitor_0_m0_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (monitor_0_m0_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (monitor_0_m0_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (monitor_0_m0_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (slave_0_s0_address),                                              //      avalon_anti_slave_0.address
		.av_write               (slave_0_s0_write),                                                //                         .write
		.av_read                (slave_0_s0_read),                                                 //                         .read
		.av_readdata            (slave_0_s0_readdata),                                             //                         .readdata
		.av_writedata           (slave_0_s0_writedata),                                            //                         .writedata
		.av_burstcount          (slave_0_s0_burstcount),                                           //                         .burstcount
		.av_byteenable          (slave_0_s0_byteenable),                                           //                         .byteenable
		.av_readdatavalid       (slave_0_s0_readdatavalid),                                        //                         .readdatavalid
		.av_waitrequest         (slave_0_s0_waitrequest),                                          //                         .waitrequest
		.av_begintransfer       (),                                                                //              (terminated)
		.av_beginbursttransfer  (),                                                                //              (terminated)
		.av_writebyteenable     (),                                                                //              (terminated)
		.av_lock                (),                                                                //              (terminated)
		.av_chipselect          (),                                                                //              (terminated)
		.av_clken               (),                                                                //              (terminated)
		.uav_clken              (1'b0),                                                            //              (terminated)
		.av_debugaccess         (),                                                                //              (terminated)
		.av_outputenable        (),                                                                //              (terminated)
		.uav_response           (),                                                                //              (terminated)
		.av_response            (2'b00),                                                           //              (terminated)
		.uav_writeresponsevalid (),                                                                //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                             //              (terminated)
	);

endmodule
