// bus_test.v

// Generated using ACDS version 21.1 842

`timescale 1 ps / 1 ps
module bus_test (
		input  wire  clk_clk,       //   clk.clk
		input  wire  reset_reset_n  // reset.reset_n
	);

	wire        simple_soma_0_m_spike_waitrequest;                     // mm_interconnect_0:simple_soma_0_m_spike_waitrequest -> simple_soma_0:m_spike_waitrequest
	wire        simple_soma_0_m_spike_write;                           // simple_soma_0:avs_m_write_spike -> mm_interconnect_0:simple_soma_0_m_spike_write
	wire  [7:0] simple_soma_0_m_spike_writedata;                       // simple_soma_0:avs_m_writedata_spike_time -> mm_interconnect_0:simple_soma_0_m_spike_writedata
	wire        mm_interconnect_0_simple_synapse_0_s_spike_write;      // mm_interconnect_0:simple_synapse_0_s_spike_write -> simple_synapse_0:avs_s_write_spike
	wire  [7:0] mm_interconnect_0_simple_synapse_0_s_spike_writedata;  // mm_interconnect_0:simple_synapse_0_s_spike_writedata -> simple_synapse_0:avs_s_writedata_spike_time
	wire  [7:0] simple_soma_0_m_synapse_readdata;                      // mm_interconnect_1:simple_soma_0_m_synapse_readdata -> simple_soma_0:avs_m_readdata_synapse
	wire        simple_soma_0_m_synapse_waitrequest;                   // mm_interconnect_1:simple_soma_0_m_synapse_waitrequest -> simple_soma_0:m_synapse_waitrequest
	wire        simple_soma_0_m_synapse_read;                          // simple_soma_0:avs_m_read_synapse -> mm_interconnect_1:simple_soma_0_m_synapse_read
	wire  [7:0] mm_interconnect_1_simple_synapse_0_s_synapse_readdata; // simple_synapse_0:avs_s_readdata_synapse -> mm_interconnect_1:simple_synapse_0_s_synapse_readdata
	wire        mm_interconnect_1_simple_synapse_0_s_synapse_read;     // mm_interconnect_1:simple_synapse_0_s_synapse_read -> simple_synapse_0:avs_s_read_synapse
	wire  [7:0] simple_soma_0_m_time_readdata;                         // mm_interconnect_2:simple_soma_0_m_time_readdata -> simple_soma_0:avs_m_readdata_time
	wire        simple_soma_0_m_time_waitrequest;                      // mm_interconnect_2:simple_soma_0_m_time_waitrequest -> simple_soma_0:m_time_waitrequest
	wire        simple_soma_0_m_time_address;                          // simple_soma_0:avs_m_address -> mm_interconnect_2:simple_soma_0_m_time_address
	wire        simple_soma_0_m_time_read;                             // simple_soma_0:avs_m_read_time -> mm_interconnect_2:simple_soma_0_m_time_read
	wire  [7:0] mm_interconnect_2_simple_synapse_0_s_time_readdata;    // simple_synapse_0:avs_s_readdata_time -> mm_interconnect_2:simple_synapse_0_s_time_readdata
	wire  [7:0] mm_interconnect_2_simple_synapse_0_s_time_address;     // mm_interconnect_2:simple_synapse_0_s_time_address -> simple_synapse_0:avs_s_address
	wire        mm_interconnect_2_simple_synapse_0_s_time_read;        // mm_interconnect_2:simple_synapse_0_s_time_read -> simple_synapse_0:avs_s_read_time
	wire        rst_controller_reset_out_reset;                        // rst_controller:reset_out -> [mm_interconnect_0:simple_soma_0_reset_sink_reset_bridge_in_reset_reset, mm_interconnect_1:simple_soma_0_reset_sink_reset_bridge_in_reset_reset, mm_interconnect_2:simple_soma_0_reset_sink_reset_bridge_in_reset_reset, simple_soma_0:rst, simple_synapse_0:rst]

	simple_soma #(
		.THRESHOLD  (10),
		.TIME_WIDTH (8)
	) simple_soma_0 (
		.clk                        (clk_clk),                             //      clock.clk
		.rst                        (rst_controller_reset_out_reset),      // reset_sink.reset
		.avs_m_read_synapse         (simple_soma_0_m_synapse_read),        //  m_synapse.read
		.avs_m_readdata_synapse     (simple_soma_0_m_synapse_readdata),    //           .readdata
		.m_synapse_waitrequest      (simple_soma_0_m_synapse_waitrequest), //           .waitrequest
		.avs_m_write_spike          (simple_soma_0_m_spike_write),         //    m_spike.write
		.avs_m_writedata_spike_time (simple_soma_0_m_spike_writedata),     //           .writedata
		.m_spike_waitrequest        (simple_soma_0_m_spike_waitrequest),   //           .waitrequest
		.avs_m_address              (simple_soma_0_m_time_address),        //     m_time.address
		.avs_m_read_time            (simple_soma_0_m_time_read),           //           .read
		.avs_m_readdata_time        (simple_soma_0_m_time_readdata),       //           .readdata
		.m_time_waitrequest         (simple_soma_0_m_time_waitrequest)     //           .waitrequest
	);

	simple_synapse #(
		.THRESHOLD  (10),
		.TIME_WIDTH (8)
	) simple_synapse_0 (
		.clk                        (clk_clk),                                               //      clock.clk
		.rst                        (rst_controller_reset_out_reset),                        // reset_sink.reset
		.avs_s_read_synapse         (mm_interconnect_1_simple_synapse_0_s_synapse_read),     //  s_synapse.read
		.avs_s_readdata_synapse     (mm_interconnect_1_simple_synapse_0_s_synapse_readdata), //           .readdata
		.avs_s_write_spike          (mm_interconnect_0_simple_synapse_0_s_spike_write),      //    s_spike.write
		.avs_s_writedata_spike_time (mm_interconnect_0_simple_synapse_0_s_spike_writedata),  //           .writedata
		.avs_s_address              (mm_interconnect_2_simple_synapse_0_s_time_address),     //     s_time.address
		.avs_s_read_time            (mm_interconnect_2_simple_synapse_0_s_time_read),        //           .read
		.avs_s_readdata_time        (mm_interconnect_2_simple_synapse_0_s_time_readdata)     //           .readdata
	);

	bus_test_mm_interconnect_0 mm_interconnect_0 (
		.clk_0_clk_clk                                        (clk_clk),                                              //                                      clk_0_clk.clk
		.simple_soma_0_reset_sink_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                       // simple_soma_0_reset_sink_reset_bridge_in_reset.reset
		.simple_soma_0_m_spike_waitrequest                    (simple_soma_0_m_spike_waitrequest),                    //                          simple_soma_0_m_spike.waitrequest
		.simple_soma_0_m_spike_write                          (simple_soma_0_m_spike_write),                          //                                               .write
		.simple_soma_0_m_spike_writedata                      (simple_soma_0_m_spike_writedata),                      //                                               .writedata
		.simple_synapse_0_s_spike_write                       (mm_interconnect_0_simple_synapse_0_s_spike_write),     //                       simple_synapse_0_s_spike.write
		.simple_synapse_0_s_spike_writedata                   (mm_interconnect_0_simple_synapse_0_s_spike_writedata)  //                                               .writedata
	);

	bus_test_mm_interconnect_1 mm_interconnect_1 (
		.clk_0_clk_clk                                        (clk_clk),                                               //                                      clk_0_clk.clk
		.simple_soma_0_reset_sink_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                        // simple_soma_0_reset_sink_reset_bridge_in_reset.reset
		.simple_soma_0_m_synapse_waitrequest                  (simple_soma_0_m_synapse_waitrequest),                   //                        simple_soma_0_m_synapse.waitrequest
		.simple_soma_0_m_synapse_read                         (simple_soma_0_m_synapse_read),                          //                                               .read
		.simple_soma_0_m_synapse_readdata                     (simple_soma_0_m_synapse_readdata),                      //                                               .readdata
		.simple_synapse_0_s_synapse_read                      (mm_interconnect_1_simple_synapse_0_s_synapse_read),     //                     simple_synapse_0_s_synapse.read
		.simple_synapse_0_s_synapse_readdata                  (mm_interconnect_1_simple_synapse_0_s_synapse_readdata)  //                                               .readdata
	);

	bus_test_mm_interconnect_2 mm_interconnect_2 (
		.clk_0_clk_clk                                        (clk_clk),                                            //                                      clk_0_clk.clk
		.simple_soma_0_reset_sink_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                     // simple_soma_0_reset_sink_reset_bridge_in_reset.reset
		.simple_soma_0_m_time_address                         (simple_soma_0_m_time_address),                       //                           simple_soma_0_m_time.address
		.simple_soma_0_m_time_waitrequest                     (simple_soma_0_m_time_waitrequest),                   //                                               .waitrequest
		.simple_soma_0_m_time_read                            (simple_soma_0_m_time_read),                          //                                               .read
		.simple_soma_0_m_time_readdata                        (simple_soma_0_m_time_readdata),                      //                                               .readdata
		.simple_synapse_0_s_time_address                      (mm_interconnect_2_simple_synapse_0_s_time_address),  //                        simple_synapse_0_s_time.address
		.simple_synapse_0_s_time_read                         (mm_interconnect_2_simple_synapse_0_s_time_read),     //                                               .read
		.simple_synapse_0_s_time_readdata                     (mm_interconnect_2_simple_synapse_0_s_time_readdata)  //                                               .readdata
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                 // reset_in0.reset
		.clk            (clk_clk),                        //       clk.clk
		.reset_out      (rst_controller_reset_out_reset), // reset_out.reset
		.reset_req      (),                               // (terminated)
		.reset_req_in0  (1'b0),                           // (terminated)
		.reset_in1      (1'b0),                           // (terminated)
		.reset_req_in1  (1'b0),                           // (terminated)
		.reset_in2      (1'b0),                           // (terminated)
		.reset_req_in2  (1'b0),                           // (terminated)
		.reset_in3      (1'b0),                           // (terminated)
		.reset_req_in3  (1'b0),                           // (terminated)
		.reset_in4      (1'b0),                           // (terminated)
		.reset_req_in4  (1'b0),                           // (terminated)
		.reset_in5      (1'b0),                           // (terminated)
		.reset_req_in5  (1'b0),                           // (terminated)
		.reset_in6      (1'b0),                           // (terminated)
		.reset_req_in6  (1'b0),                           // (terminated)
		.reset_in7      (1'b0),                           // (terminated)
		.reset_req_in7  (1'b0),                           // (terminated)
		.reset_in8      (1'b0),                           // (terminated)
		.reset_req_in8  (1'b0),                           // (terminated)
		.reset_in9      (1'b0),                           // (terminated)
		.reset_req_in9  (1'b0),                           // (terminated)
		.reset_in10     (1'b0),                           // (terminated)
		.reset_req_in10 (1'b0),                           // (terminated)
		.reset_in11     (1'b0),                           // (terminated)
		.reset_req_in11 (1'b0),                           // (terminated)
		.reset_in12     (1'b0),                           // (terminated)
		.reset_req_in12 (1'b0),                           // (terminated)
		.reset_in13     (1'b0),                           // (terminated)
		.reset_req_in13 (1'b0),                           // (terminated)
		.reset_in14     (1'b0),                           // (terminated)
		.reset_req_in14 (1'b0),                           // (terminated)
		.reset_in15     (1'b0),                           // (terminated)
		.reset_req_in15 (1'b0)                            // (terminated)
	);

endmodule
