# TCL File Generated by Component Editor 21.1
# Mon Mar 07 12:34:58 KST 2022
# DO NOT MODIFY


# 
# simple_soma_SM "simple soma State Machine" v1.0
#  2022.03.07.12:34:58
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module simple_soma_SM
# 
set_module_property DESCRIPTION ""
set_module_property NAME simple_soma_SM
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "simple soma State Machine"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL simple_soma_sm
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file simple_soma_sm.vhd VHDL PATH src/simple_soma_sm.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter THRESHOLD INTEGER 10
set_parameter_property THRESHOLD DEFAULT_VALUE 10
set_parameter_property THRESHOLD DISPLAY_NAME THRESHOLD
set_parameter_property THRESHOLD TYPE INTEGER
set_parameter_property THRESHOLD UNITS None
set_parameter_property THRESHOLD ALLOWED_RANGES -2147483648:2147483647
set_parameter_property THRESHOLD HDL_PARAMETER true
add_parameter DATA_WIDTH INTEGER 8
set_parameter_property DATA_WIDTH DEFAULT_VALUE 8
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter ADDR_WIDTH INTEGER 7
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 7
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH TYPE INTEGER
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
add_parameter UPLOAD_SERVER_ADDRESS STD_LOGIC_VECTOR 1
set_parameter_property UPLOAD_SERVER_ADDRESS DEFAULT_VALUE 1
set_parameter_property UPLOAD_SERVER_ADDRESS DISPLAY_NAME UPLOAD_SERVER_ADDRESS
set_parameter_property UPLOAD_SERVER_ADDRESS TYPE STD_LOGIC_VECTOR
set_parameter_property UPLOAD_SERVER_ADDRESS UNITS None
set_parameter_property UPLOAD_SERVER_ADDRESS ALLOWED_RANGES 0:255
set_parameter_property UPLOAD_SERVER_ADDRESS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst reset Input 1


# 
# connection point pushspike
# 
add_interface pushspike avalon start
set_interface_property pushspike addressUnits SYMBOLS
set_interface_property pushspike associatedClock clock
set_interface_property pushspike associatedReset reset_sink
set_interface_property pushspike bitsPerSymbol 8
set_interface_property pushspike burstOnBurstBoundariesOnly false
set_interface_property pushspike burstcountUnits WORDS
set_interface_property pushspike doStreamReads false
set_interface_property pushspike doStreamWrites false
set_interface_property pushspike holdTime 0
set_interface_property pushspike linewrapBursts false
set_interface_property pushspike maximumPendingReadTransactions 0
set_interface_property pushspike maximumPendingWriteTransactions 0
set_interface_property pushspike readLatency 0
set_interface_property pushspike readWaitTime 1
set_interface_property pushspike setupTime 0
set_interface_property pushspike timingUnits Cycles
set_interface_property pushspike writeWaitTime 0
set_interface_property pushspike ENABLED true
set_interface_property pushspike EXPORT_OF ""
set_interface_property pushspike PORT_NAME_MAP ""
set_interface_property pushspike CMSIS_SVD_VARIABLES ""
set_interface_property pushspike SVD_ADDRESS_GROUP ""

add_interface_port pushspike avm_pushSpike_address address Output "(addr_width) - (0) + 1"
add_interface_port pushspike avm_pushSpike_waitrequest waitrequest Input 1
add_interface_port pushspike avm_pushSpike_write write Output 1
add_interface_port pushspike avm_pushSpike_writedata writedata Output "((data_width-1)) - (0) + 1"


# 
# connection point pullsynapse
# 
add_interface pullsynapse avalon end
set_interface_property pullsynapse addressUnits WORDS
set_interface_property pullsynapse associatedClock clock
set_interface_property pullsynapse associatedReset reset_sink
set_interface_property pullsynapse bitsPerSymbol 8
set_interface_property pullsynapse burstOnBurstBoundariesOnly false
set_interface_property pullsynapse burstcountUnits WORDS
set_interface_property pullsynapse explicitAddressSpan 0
set_interface_property pullsynapse holdTime 0
set_interface_property pullsynapse linewrapBursts false
set_interface_property pullsynapse maximumPendingReadTransactions 0
set_interface_property pullsynapse maximumPendingWriteTransactions 0
set_interface_property pullsynapse readLatency 0
set_interface_property pullsynapse readWaitTime 1
set_interface_property pullsynapse setupTime 0
set_interface_property pullsynapse timingUnits Cycles
set_interface_property pullsynapse writeWaitTime 0
set_interface_property pullsynapse ENABLED true
set_interface_property pullsynapse EXPORT_OF ""
set_interface_property pullsynapse PORT_NAME_MAP ""
set_interface_property pullsynapse CMSIS_SVD_VARIABLES ""
set_interface_property pullsynapse SVD_ADDRESS_GROUP ""

add_interface_port pullsynapse avs_pullSynapse_address address Input "(addr_width) - (0) + 1"
add_interface_port pullsynapse avs_pullSynapse_write write Input 1
add_interface_port pullsynapse avs_pullSynapse_writedata writedata Input "((data_width-1)) - (0) + 1"
set_interface_assignment pullsynapse embeddedsw.configuration.isFlash 0
set_interface_assignment pullsynapse embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment pullsynapse embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment pullsynapse embeddedsw.configuration.isPrintableDevice 0

