# TCL File Generated by Component Editor 21.1
# Fri Mar 04 17:04:40 KST 2022
# DO NOT MODIFY


# 
# simple_soma_SM "simple soma State Machine" v1.0
#  2022.03.04.17:04:40
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module simple_soma_SM
# 
set_module_property DESCRIPTION ""
set_module_property NAME simple_soma_SM
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "simple soma State Machine"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL simple_soma_sm
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file simple_soma_sm.vhd VHDL PATH src/simple_soma_sm.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter THRESHOLD INTEGER 10
set_parameter_property THRESHOLD DEFAULT_VALUE 10
set_parameter_property THRESHOLD DISPLAY_NAME THRESHOLD
set_parameter_property THRESHOLD TYPE INTEGER
set_parameter_property THRESHOLD UNITS None
set_parameter_property THRESHOLD HDL_PARAMETER true
add_parameter TIME_WIDTH INTEGER 8
set_parameter_property TIME_WIDTH DEFAULT_VALUE 8
set_parameter_property TIME_WIDTH DISPLAY_NAME TIME_WIDTH
set_parameter_property TIME_WIDTH TYPE INTEGER
set_parameter_property TIME_WIDTH UNITS None
set_parameter_property TIME_WIDTH HDL_PARAMETER true
add_parameter ADDR_WIDTH INTEGER 7
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 7
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH TYPE INTEGER
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
add_parameter UPLOAD_SERVER_ADDRESS STD_LOGIC_VECTOR 1
set_parameter_property UPLOAD_SERVER_ADDRESS DEFAULT_VALUE 1
set_parameter_property UPLOAD_SERVER_ADDRESS DISPLAY_NAME UPLOAD_SERVER_ADDRESS
set_parameter_property UPLOAD_SERVER_ADDRESS TYPE STD_LOGIC_VECTOR
set_parameter_property UPLOAD_SERVER_ADDRESS UNITS None
set_parameter_property UPLOAD_SERVER_ADDRESS ALLOWED_RANGES 0:255
set_parameter_property UPLOAD_SERVER_ADDRESS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clock
set_interface_property s0 associatedReset reset_sink
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 maximumPendingWriteTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avs_s0_address address Input "(addr_width) - (0) + 1"
add_interface_port s0 avs_s0_write_synapse write Input 1
add_interface_port s0 avs_s0_writedata_synapse writedata Input "((time_width-1)) - (0) + 1"
add_interface_port s0 avs_s0_response_synapse response Output 2
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset_sink
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master avs_m0_address address Output "(addr_width) - (0) + 1"
add_interface_port avalon_master avs_m0_waitrequest waitrequest Input 1
add_interface_port avalon_master avs_m0_write_spike write Output 1
add_interface_port avalon_master avs_m0_writedata_spike_time writedata Output "((time_width-1)) - (0) + 1"
add_interface_port avalon_master avs_m0_response_spike response Input 2


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst reset Input 1

