# TCL File Generated by Component Editor 21.1
# Sun Apr 03 16:49:10 KST 2022
# DO NOT MODIFY


# 
# SOMA "SOMA_UNIT" v1.0
#  2022.04.03.16:49:10
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module SOMA
# 
set_module_property DESCRIPTION ""
set_module_property NAME SOMA
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME SOMA_UNIT
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL new_component
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file fixed_float_types_c.vhdl VHDL PATH fixed_float/fixed_float_types_c.vhdl TOP_LEVEL_FILE
add_fileset_file fixed_noresize.vhdl VHDL PATH fixed_float/fixed_noresize.vhdl
add_fileset_file fixed_pkg_c.vhdl VHDL PATH fixed_float/fixed_pkg_c.vhdl
add_fileset_file fixed_synth.vhdl VHDL PATH fixed_float/fixed_synth.vhdl
add_fileset_file soma.vhd VHDL PATH submission/soma.vhd
add_fileset_file properties_pack.vhd VHDL PATH submission/properties_pack.vhd


# 
# parameters
# 


# 
# display items
# 

