# TCL File Generated by Component Editor 21.1
# Sat Mar 26 19:28:52 KST 2022
# DO NOT MODIFY


# 
# ram_controller "sample" v1.0
#  2022.03.26.19:28:52
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ram_controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME ram_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME sample
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ram_control
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ram_control.vhd VHDL PATH ram_control.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point ADDR_in
# 
add_interface ADDR_in conduit end
set_interface_property ADDR_in associatedClock clock
set_interface_property ADDR_in associatedReset ""
set_interface_property ADDR_in ENABLED true
set_interface_property ADDR_in EXPORT_OF ""
set_interface_property ADDR_in PORT_NAME_MAP ""
set_interface_property ADDR_in CMSIS_SVD_VARIABLES ""
set_interface_property ADDR_in SVD_ADDRESS_GROUP ""

add_interface_port ADDR_in ADDR_in conduit Input 4


# 
# connection point W_EN_out
# 
add_interface W_EN_out conduit end
set_interface_property W_EN_out associatedClock clock
set_interface_property W_EN_out associatedReset ""
set_interface_property W_EN_out ENABLED true
set_interface_property W_EN_out EXPORT_OF ""
set_interface_property W_EN_out PORT_NAME_MAP ""
set_interface_property W_EN_out CMSIS_SVD_VARIABLES ""
set_interface_property W_EN_out SVD_ADDRESS_GROUP ""

add_interface_port W_EN_out W_EN_out conduit Output 1


# 
# connection point W_EN_in
# 
add_interface W_EN_in conduit end
set_interface_property W_EN_in associatedClock clock
set_interface_property W_EN_in associatedReset ""
set_interface_property W_EN_in ENABLED true
set_interface_property W_EN_in EXPORT_OF ""
set_interface_property W_EN_in PORT_NAME_MAP ""
set_interface_property W_EN_in CMSIS_SVD_VARIABLES ""
set_interface_property W_EN_in SVD_ADDRESS_GROUP ""

add_interface_port W_EN_in W_EN_in conduit Input 1


# 
# connection point R_EN_out
# 
add_interface R_EN_out conduit end
set_interface_property R_EN_out associatedClock clock
set_interface_property R_EN_out associatedReset ""
set_interface_property R_EN_out ENABLED true
set_interface_property R_EN_out EXPORT_OF ""
set_interface_property R_EN_out PORT_NAME_MAP ""
set_interface_property R_EN_out CMSIS_SVD_VARIABLES ""
set_interface_property R_EN_out SVD_ADDRESS_GROUP ""

add_interface_port R_EN_out R_EN_out conduit Output 1


# 
# connection point R_EN_in
# 
add_interface R_EN_in conduit end
set_interface_property R_EN_in associatedClock clock
set_interface_property R_EN_in associatedReset ""
set_interface_property R_EN_in ENABLED true
set_interface_property R_EN_in EXPORT_OF ""
set_interface_property R_EN_in PORT_NAME_MAP ""
set_interface_property R_EN_in CMSIS_SVD_VARIABLES ""
set_interface_property R_EN_in SVD_ADDRESS_GROUP ""

add_interface_port R_EN_in R_EN_in conduit Input 1


# 
# connection point DATA_OUT_out
# 
add_interface DATA_OUT_out conduit end
set_interface_property DATA_OUT_out associatedClock clock
set_interface_property DATA_OUT_out associatedReset ""
set_interface_property DATA_OUT_out ENABLED true
set_interface_property DATA_OUT_out EXPORT_OF ""
set_interface_property DATA_OUT_out PORT_NAME_MAP ""
set_interface_property DATA_OUT_out CMSIS_SVD_VARIABLES ""
set_interface_property DATA_OUT_out SVD_ADDRESS_GROUP ""

add_interface_port DATA_OUT_out DATA_OUT_out conduit Output 16


# 
# connection point DATA_IN_out
# 
add_interface DATA_IN_out conduit end
set_interface_property DATA_IN_out associatedClock clock
set_interface_property DATA_IN_out associatedReset ""
set_interface_property DATA_IN_out ENABLED true
set_interface_property DATA_IN_out EXPORT_OF ""
set_interface_property DATA_IN_out PORT_NAME_MAP ""
set_interface_property DATA_IN_out CMSIS_SVD_VARIABLES ""
set_interface_property DATA_IN_out SVD_ADDRESS_GROUP ""

add_interface_port DATA_IN_out DATA_IN_out conduit Output 16


# 
# connection point DATA_OUT_in
# 
add_interface DATA_OUT_in conduit end
set_interface_property DATA_OUT_in associatedClock clock
set_interface_property DATA_OUT_in associatedReset ""
set_interface_property DATA_OUT_in ENABLED true
set_interface_property DATA_OUT_in EXPORT_OF ""
set_interface_property DATA_OUT_in PORT_NAME_MAP ""
set_interface_property DATA_OUT_in CMSIS_SVD_VARIABLES ""
set_interface_property DATA_OUT_in SVD_ADDRESS_GROUP ""

add_interface_port DATA_OUT_in DATA_OUT_in conduit Input 16


# 
# connection point DATA_IN_in
# 
add_interface DATA_IN_in conduit end
set_interface_property DATA_IN_in associatedClock clock
set_interface_property DATA_IN_in associatedReset ""
set_interface_property DATA_IN_in ENABLED true
set_interface_property DATA_IN_in EXPORT_OF ""
set_interface_property DATA_IN_in PORT_NAME_MAP ""
set_interface_property DATA_IN_in CMSIS_SVD_VARIABLES ""
set_interface_property DATA_IN_in SVD_ADDRESS_GROUP ""

add_interface_port DATA_IN_in DATA_IN_in conduit Input 16


# 
# connection point ADDR_out
# 
add_interface ADDR_out conduit end
set_interface_property ADDR_out associatedClock clock
set_interface_property ADDR_out associatedReset ""
set_interface_property ADDR_out ENABLED true
set_interface_property ADDR_out EXPORT_OF ""
set_interface_property ADDR_out PORT_NAME_MAP ""
set_interface_property ADDR_out CMSIS_SVD_VARIABLES ""
set_interface_property ADDR_out SVD_ADDRESS_GROUP ""

add_interface_port ADDR_out ADDR_out conduit Output 4

