# TCL File Generated by Component Editor 21.1
# Sat Mar 26 19:30:30 KST 2022
# DO NOT MODIFY


# 
# ram "ram" v1.0
#  2022.03.26.19:30:30
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ram
# 
set_module_property DESCRIPTION ""
set_module_property NAME ram
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ram
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ram
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ram.vhd VHDL PATH ram.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point data
# 
add_interface data conduit end
set_interface_property data associatedClock ""
set_interface_property data associatedReset ""
set_interface_property data ENABLED true
set_interface_property data EXPORT_OF ""
set_interface_property data PORT_NAME_MAP ""
set_interface_property data CMSIS_SVD_VARIABLES ""
set_interface_property data SVD_ADDRESS_GROUP ""

add_interface_port data data conduit Input 16


# 
# connection point address
# 
add_interface address conduit end
set_interface_property address associatedClock ""
set_interface_property address associatedReset ""
set_interface_property address ENABLED true
set_interface_property address EXPORT_OF ""
set_interface_property address PORT_NAME_MAP ""
set_interface_property address CMSIS_SVD_VARIABLES ""
set_interface_property address SVD_ADDRESS_GROUP ""

add_interface_port address address conduit Input 4


# 
# connection point q
# 
add_interface q conduit end
set_interface_property q associatedClock ""
set_interface_property q associatedReset ""
set_interface_property q ENABLED true
set_interface_property q EXPORT_OF ""
set_interface_property q PORT_NAME_MAP ""
set_interface_property q CMSIS_SVD_VARIABLES ""
set_interface_property q SVD_ADDRESS_GROUP ""

add_interface_port q q conduit Output 16


# 
# connection point wren
# 
add_interface wren conduit end
set_interface_property wren associatedClock ""
set_interface_property wren associatedReset ""
set_interface_property wren ENABLED true
set_interface_property wren EXPORT_OF ""
set_interface_property wren PORT_NAME_MAP ""
set_interface_property wren CMSIS_SVD_VARIABLES ""
set_interface_property wren SVD_ADDRESS_GROUP ""

add_interface_port wren wren conduit Input 1


# 
# connection point rden
# 
add_interface rden conduit end
set_interface_property rden associatedClock ""
set_interface_property rden associatedReset ""
set_interface_property rden ENABLED true
set_interface_property rden EXPORT_OF ""
set_interface_property rden PORT_NAME_MAP ""
set_interface_property rden CMSIS_SVD_VARIABLES ""
set_interface_property rden SVD_ADDRESS_GROUP ""

add_interface_port rden rden conduit Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1

