# TCL File Generated by Component Editor 21.1
# Wed Mar 16 12:21:02 KST 2022
# DO NOT MODIFY


# 
# slave_0 "slave_0" v1.0
#  2022.03.16.12:21:02
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module slave_0
# 
set_module_property DESCRIPTION ""
set_module_property NAME slave_0
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME slave_0
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL addr_slave
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file addr_slave.vhd VHDL PATH ../src/addr_slave.vhd TOP_LEVEL_FILE

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file addr_slave.vhd VHDL PATH ../src/addr_slave.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point coe_dbg_wait_pin
# 
add_interface coe_dbg_wait_pin conduit end
set_interface_property coe_dbg_wait_pin associatedClock clk
set_interface_property coe_dbg_wait_pin associatedReset ""
set_interface_property coe_dbg_wait_pin ENABLED true
set_interface_property coe_dbg_wait_pin EXPORT_OF ""
set_interface_property coe_dbg_wait_pin PORT_NAME_MAP ""
set_interface_property coe_dbg_wait_pin CMSIS_SVD_VARIABLES ""
set_interface_property coe_dbg_wait_pin SVD_ADDRESS_GROUP ""

add_interface_port coe_dbg_wait_pin coe_dbg_wait_pin conduit Output 1


# 
# connection point coe_dbg_data
# 
add_interface coe_dbg_data conduit end
set_interface_property coe_dbg_data associatedClock clk
set_interface_property coe_dbg_data associatedReset ""
set_interface_property coe_dbg_data ENABLED true
set_interface_property coe_dbg_data EXPORT_OF ""
set_interface_property coe_dbg_data PORT_NAME_MAP ""
set_interface_property coe_dbg_data CMSIS_SVD_VARIABLES ""
set_interface_property coe_dbg_data SVD_ADDRESS_GROUP ""

add_interface_port coe_dbg_data coe_dbg_data conduit Output 32


# 
# connection point coe_dbg_data_write
# 
add_interface coe_dbg_data_write conduit end
set_interface_property coe_dbg_data_write associatedClock clk
set_interface_property coe_dbg_data_write associatedReset ""
set_interface_property coe_dbg_data_write ENABLED true
set_interface_property coe_dbg_data_write EXPORT_OF ""
set_interface_property coe_dbg_data_write PORT_NAME_MAP ""
set_interface_property coe_dbg_data_write CMSIS_SVD_VARIABLES ""
set_interface_property coe_dbg_data_write SVD_ADDRESS_GROUP ""

add_interface_port coe_dbg_data_write coe_dbg_data_write conduit Output 32


# 
# connection point coe_out_pin
# 
add_interface coe_out_pin conduit end
set_interface_property coe_out_pin associatedClock clk
set_interface_property coe_out_pin associatedReset ""
set_interface_property coe_out_pin ENABLED true
set_interface_property coe_out_pin EXPORT_OF ""
set_interface_property coe_out_pin PORT_NAME_MAP ""
set_interface_property coe_out_pin CMSIS_SVD_VARIABLES ""
set_interface_property coe_out_pin SVD_ADDRESS_GROUP ""

add_interface_port coe_out_pin coe_out_pin conduit Output 32


# 
# connection point coe_dbg_out_en
# 
add_interface coe_dbg_out_en conduit end
set_interface_property coe_dbg_out_en associatedClock clk
set_interface_property coe_dbg_out_en associatedReset ""
set_interface_property coe_dbg_out_en ENABLED true
set_interface_property coe_dbg_out_en EXPORT_OF ""
set_interface_property coe_dbg_out_en PORT_NAME_MAP ""
set_interface_property coe_dbg_out_en CMSIS_SVD_VARIABLES ""
set_interface_property coe_dbg_out_en SVD_ADDRESS_GROUP ""

add_interface_port coe_dbg_out_en coe_dbg_out_en conduit Output 1


# 
# connection point coe_wait_pin
# 
add_interface coe_wait_pin conduit end
set_interface_property coe_wait_pin associatedClock clk
set_interface_property coe_wait_pin associatedReset ""
set_interface_property coe_wait_pin ENABLED true
set_interface_property coe_wait_pin EXPORT_OF ""
set_interface_property coe_wait_pin PORT_NAME_MAP ""
set_interface_property coe_wait_pin CMSIS_SVD_VARIABLES ""
set_interface_property coe_wait_pin SVD_ADDRESS_GROUP ""

add_interface_port coe_wait_pin coe_wait_pin conduit Input 1


# 
# connection point coe_out_en
# 
add_interface coe_out_en conduit end
set_interface_property coe_out_en associatedClock clk
set_interface_property coe_out_en associatedReset ""
set_interface_property coe_out_en ENABLED true
set_interface_property coe_out_en EXPORT_OF ""
set_interface_property coe_out_en PORT_NAME_MAP ""
set_interface_property coe_out_en CMSIS_SVD_VARIABLES ""
set_interface_property coe_out_en SVD_ADDRESS_GROUP ""

add_interface_port coe_out_en coe_out_en conduit Input 1


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clk
set_interface_property s0 associatedReset clk_reset
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 maximumPendingWriteTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avs_address address Input 12
add_interface_port s0 avs_waitrequest waitrequest Output 1
add_interface_port s0 avs_write write Input 1
add_interface_port s0 avs_writedata writedata Input 32
add_interface_port s0 avs_byteenable byteenable Input 4
add_interface_port s0 avs_read read Input 1
add_interface_port s0 avs_readdata readdata Output 32
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clk_reset
# 
add_interface clk_reset reset end
set_interface_property clk_reset associatedClock clk
set_interface_property clk_reset synchronousEdges DEASSERT
set_interface_property clk_reset ENABLED true
set_interface_property clk_reset EXPORT_OF ""
set_interface_property clk_reset PORT_NAME_MAP ""
set_interface_property clk_reset CMSIS_SVD_VARIABLES ""
set_interface_property clk_reset SVD_ADDRESS_GROUP ""

add_interface_port clk_reset rst reset Input 1


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1

